wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: true
batch_size:
  value: 32
dropout_1:
  value: 0
dropout_2:
  value: 0
dropout_3:
  value: 0.3
dropout_4:
  value: 0.3
epochs:
  value: 50
fc_layer_size_1:
  value: 256
fc_layer_size_2:
  value: 512
fc_layer_size_3:
  value: 4000
gradient_clipping:
  value: true
lr:
  value: 0.001
lr_scheduler:
  value: false
momentum:
  value: 0
optimizer:
  value: sgd
weight_decay:
  value: 0
