wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value: 0
dropout_2:
  value: 0.5
dropout_3:
  value: 0.5
dropout_4:
  value: 0.3
epochs:
  value: 50
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 1024
fc_layer_size_3:
  value: 256
gradient_clipping:
  value: true
lr:
  value: 0.1
lr_scheduler:
  value: false
momentum:
  value: 0
optimizer:
  value: sgd
weight_decay:
  value: 0.005
