wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dropout_1:
  value: 0.4
dropout_2:
  value: 0.5
dropout_3:
  value: 0
dropout_4:
  value: 0
epochs:
  value: 50
fc_layer_size_1:
  value: 256
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 128
gradient_clipping:
  value: false
lr:
  value: 0.001
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
