wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value: 0.3
dropout_2:
  value: 0.4
dropout_3:
  value: 0.3
dropout_4:
  value: 0.5
epochs:
  value: 50
fc_layer_size_1:
  value: 1024
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: false
lr:
  value: 0.001
lr_scheduler:
  value: true
momentum:
  value: 0.9
optimizer:
  value: sgd
weight_decay:
  value: 0.005
