wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value: 0
dropout_2:
  value: 0
dropout_3:
  value: 0.5
dropout_4:
  value: 0.5
epochs:
  value: 50
fc_layer_size_1:
  value: 512
fc_layer_size_2:
  value: 256
fc_layer_size_3:
  value: 1000
gradient_clipping:
  value: false
lr:
  value: 1.0e-05
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: rmsprop
weight_decay:
  value: 0.1
