wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: false
batch_size:
  value: 128
dropout_1:
  value: 0.3
dropout_2:
  value: 0
dropout_3:
  value: 0
dropout_4:
  value: 0.5
epochs:
  value: 50
fc_layer_size_1:
  value: 1000
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 1024
gradient_clipping:
  value: true
lr:
  value: 0.1
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: sam_sgd
weight_decay:
  value: 1.0e-05
