wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dropout_1:
  value: 0
dropout_2:
  value: 0.4
dropout_3:
  value: 0.4
dropout_4:
  value: 0.5
epochs:
  value: 50
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 1000
fc_layer_size_3:
  value: 256
gradient_clipping:
  value: true
lr:
  value: 0.005
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: rmsprop
weight_decay:
  value: 0
