wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dropout_1:
  value: 0.3
dropout_2:
  value: 0.5
dropout_3:
  value: 0.5
dropout_4:
  value: 0.4
epochs:
  value: 50
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: true
lr:
  value: 1.0e-05
lr_scheduler:
  value: true
momentum:
  value: 0.9
optimizer:
  value: adam
weight_decay:
  value: 0.005
