wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dropout_1:
  value:
  - b
  - 0.3
dropout_2:
  value:
  - a
  - 0.4
dropout_3:
  value:
  - a
  - 0.5
dropout_4:
  value:
  - a
  - 0.3
epochs:
  value: 5
fc_layer_size_1:
  value: 1000
fc_layer_size_2:
  value: 1000
fc_layer_size_3:
  value: 1024
gradient_clipping:
  value: true
lr:
  value: 0.001
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: adagrad
weight_decay:
  value: 0.0005
