wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value:
  - a
  - 0.3
dropout_2:
  value:
  - b
  - 0
dropout_3:
  value:
  - a
  - 0.5
dropout_4:
  value:
  - a
  - 0.5
epochs:
  value: 5
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 128
gradient_clipping:
  value: false
lr:
  value: 1.0e-05
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: adam
weight_decay:
  value: 0.001
