wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 128
dropout_1:
  value:
  - b
  - 0.3
dropout_2:
  value:
  - a
  - 0.5
dropout_3:
  value:
  - b
  - 0
dropout_4:
  value:
  - b
  - 0.5
epochs:
  value: 5
fc_layer_size_1:
  value: 1000
fc_layer_size_2:
  value: 1024
fc_layer_size_3:
  value: 1000
gradient_clipping:
  value: false
lr:
  value: 0.1
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: adagrad
weight_decay:
  value: 0.0005
