wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: true
batch_size:
  value: 128
dropout_1:
  value:
  - a
  - 0.4
dropout_2:
  value:
  - a
  - 0
dropout_3:
  value:
  - a
  - 0
dropout_4:
  value:
  - b
  - 0
epochs:
  value: 5
fc_layer_size_1:
  value: 512
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: false
lr:
  value: 0.0005
lr_scheduler:
  value: false
momentum:
  value: 0
optimizer:
  value: rmsprop
weight_decay:
  value: 0.1
