wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 128
dropout_1:
  value:
  - a
  - 0.4
dropout_2:
  value:
  - a
  - 0.3
dropout_3:
  value:
  - b
  - 0
dropout_4:
  value:
  - b
  - 0
epochs:
  value: 5
fc_layer_size_1:
  value: 512
fc_layer_size_2:
  value: 256
fc_layer_size_3:
  value: 4000
gradient_clipping:
  value: false
lr:
  value: 0.001
lr_scheduler:
  value: false
momentum:
  value: 0
optimizer:
  value: sgd
weight_decay:
  value: 0.1
