wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: true
batch_size:
  value: 32
dropout_1:
  value:
  - a
  - 0.3
dropout_2:
  value:
  - b
  - 0
dropout_3:
  value:
  - b
  - 0.4
dropout_4:
  value:
  - a
  - 0
epochs:
  value: 5
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 4000
fc_layer_size_3:
  value: 256
gradient_clipping:
  value: false
lr:
  value: 0.001
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: rmsprop
weight_decay:
  value: 1.0e-05
