wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value:
  - a
  - 0
dropout_2:
  value:
  - a
  - 0.5
dropout_3:
  value:
  - a
  - 0
dropout_4:
  value:
  - b
  - 0
epochs:
  value: 5
fc_layer_size_1:
  value: 1024
fc_layer_size_2:
  value: 256
fc_layer_size_3:
  value: 128
gradient_clipping:
  value: true
lr:
  value: 0.0005
lr_scheduler:
  value: false
momentum:
  value: 0
optimizer:
  value: rmsprop
weight_decay:
  value: 0.001
