wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: true
batch_size:
  value: 64
dropout_1:
  value:
  - a
  - 0.4
dropout_2:
  value:
  - b
  - 0
dropout_3:
  value:
  - b
  - 0.5
dropout_4:
  value:
  - b
  - 0.5
epochs:
  value: 5
fc_layer_size_1:
  value: 1024
fc_layer_size_2:
  value: 1024
fc_layer_size_3:
  value: 128
gradient_clipping:
  value: true
lr:
  value: 0.1
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: sgd
weight_decay:
  value: 0.001
