wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: true
batch_size:
  value: 128
dropout_1:
  value:
  - a
  - 0
dropout_2:
  value:
  - b
  - 0.4
dropout_3:
  value:
  - a
  - 0.3
dropout_4:
  value:
  - a
  - 0.4
epochs:
  value: 50
fc_layer_size_1:
  value: 256
fc_layer_size_2:
  value: 128
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: true
lr:
  value: 0.005
lr_scheduler:
  value: true
momentum:
  value: 0.9
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
