wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value: 0
dropout_2:
  value: 0
dropout_3:
  value: 0.5
dropout_4:
  value: 0.5
epochs:
  value: 50
fc_layer_size_1:
  value: 4000
fc_layer_size_2:
  value: 256
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: false
lr:
  value: 0.0005
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: sgd
weight_decay:
  value: 0.1
