wandb_version: 1

Nesterov:
  value: false
batch_norm:
  value: true
batch_size:
  value: 128
dropout_1:
  value:
  - a
  - 0.4
dropout_2:
  value:
  - a
  - 0.3
dropout_3:
  value:
  - b
  - 0
dropout_4:
  value:
  - b
  - 0.4
epochs:
  value: 5
fc_layer_size_1:
  value: 1000
fc_layer_size_2:
  value: 4000
fc_layer_size_3:
  value: 1024
gradient_clipping:
  value: true
lr:
  value: 0.005
lr_scheduler:
  value: true
momentum:
  value: 0
optimizer:
  value: adam
weight_decay:
  value: 0
