wandb_version: 1

Nesterov:
  value: true
batch_norm:
  value: false
batch_size:
  value: 64
dropout_1:
  value:
  - b
  - 0.3
dropout_2:
  value:
  - a
  - 0
dropout_3:
  value:
  - b
  - 0
dropout_4:
  value:
  - a
  - 0
epochs:
  value: 5
fc_layer_size_1:
  value: 512
fc_layer_size_2:
  value: 256
fc_layer_size_3:
  value: 512
gradient_clipping:
  value: true
lr:
  value: 0.001
lr_scheduler:
  value: false
momentum:
  value: 0.9
optimizer:
  value: rmsprop
weight_decay:
  value: 1.0e-05
