wandb_version: 1

Nesterov:
  desc: null
  value: false
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
dropout_1:
  desc: null
  value:
  - b
  - 0
dropout_2:
  desc: null
  value:
  - b
  - 0.5
dropout_3:
  desc: null
  value:
  - b
  - 0
dropout_4:
  desc: null
  value:
  - a
  - 0
epochs:
  desc: null
  value: 5
fc_layer_size_1:
  desc: null
  value: 1000
fc_layer_size_2:
  desc: null
  value: 256
fc_layer_size_3:
  desc: null
  value: 128
gradient_clipping:
  desc: null
  value: false
lr:
  desc: null
  value: 1.0e-05
lr_scheduler:
  desc: null
  value: true
momentum:
  desc: null
  value: 0.9
optimizer:
  desc: null
  value: sam_sgd
weight_decay:
  desc: null
  value: 0.1
_items:
  desc: null
  value:
    Nesterov: false
    batch_norm: false
    batch_size: 128
    dropout_1:
    - b
    - 0
    dropout_2:
    - b
    - 0.5
    dropout_3:
    - b
    - 0
    dropout_4:
    - a
    - 0
    epochs: 5
    fc_layer_size_1: 1000
    fc_layer_size_2: 256
    fc_layer_size_3: 128
    gradient_clipping: false
    lr: 1.0e-05
    lr_scheduler: true
    momentum: 0.9
    optimizer: sam_sgd
    weight_decay: 0.1
    _wandb: {}
_locked:
  desc: null
  value:
    Nesterov: 0
    batch_norm: 0
    batch_size: 0
    dropout_1: 0
    dropout_2: 0
    dropout_3: 0
    dropout_4: 0
    epochs: 0
    fc_layer_size_1: 0
    fc_layer_size_2: 0
    fc_layer_size_3: 0
    gradient_clipping: 0
    lr: 0
    lr_scheduler: 0
    momentum: 0
    optimizer: 0
    weight_decay: 0
_users:
  desc: null
  value:
    sweep: 0
_users_inv:
  desc: null
  value:
    '0': sweep
_users_cnt:
  desc: null
  value: 1
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value:
    _args: []
    _aws_lambda: false
    _async_upload_concurrency_limit: null
    _cli_only_mode: null
    _colab: false
    _cuda: null
    _disable_meta: false
    _disable_service: false
    _disable_setproctitle: false
    _disable_stats: false
    _disable_viewer: null
    _disable_machine_info: false
    _except_exit: true
    _executable: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\venv\Scripts\python.exe
    _extra_http_headers: null
    _file_stream_retry_max: 125
    _file_stream_retry_wait_min_seconds: 2
    _file_stream_retry_wait_max_seconds: 60
    _file_stream_timeout_seconds: 180
    _file_uploader_retry_max: 10
    _file_uploader_retry_wait_min_seconds: 2
    _file_uploader_retry_wait_max_seconds: 60
    _file_uploader_timeout_seconds: 0
    _flow_control_custom: false
    _flow_control_disabled: false
    _graphql_retry_max: 10
    _graphql_retry_wait_min_seconds: 2
    _graphql_retry_wait_max_seconds: 60
    _graphql_timeout_seconds: 30
    _internal_check_process: 8.0
    _internal_queue_timeout: 2.0
    _ipython: false
    _jupyter: false
    _jupyter_name: null
    _jupyter_path: null
    _jupyter_root: null
    _kaggle: false
    _live_policy_rate_limit: null
    _live_policy_wait_time: null
    _log_level: 10
    _network_buffer: null
    _noop: false
    _notebook: false
    _offline: false
    _sync: false
    _os: Windows-10-10.0.22621-SP0
    _platform: windows
    _proxies: null
    _python: 3.10.4
    _runqueue_item_id: null
    _require_nexus: false
    _save_requirements: true
    _service_transport: null
    _service_wait: 30.0
    _start_datetime: '20231106_171745'
    _start_time: 1699283865.6533604
    _stats_pid: 4456
    _stats_sample_rate_seconds: 2.0
    _stats_samples_to_average: 15
    _stats_join_assets: true
    _stats_neuron_monitor_config_path: null
    _stats_open_metrics_endpoints: null
    _stats_open_metrics_filters:
    - .*
    _stats_disk_paths:
    - /
    _stats_buffer_size: 0
    _tmp_code_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\tmp\code
    _tracelog: null
    _unsaved_keys: null
    _windows: true
    allow_val_change: null
    anonymous: null
    api_key: null
    azure_account_url_to_access_key: null
    base_url: https://api.wandb.ai
    code_dir: null
    colab_url: null
    config_paths: null
    console: wrap
    deployment: cloud
    disable_code: false
    disable_git: false
    disable_hints: null
    disable_job_creation: false
    disabled: false
    docker: null
    email: corina.dimitriu.01@gmail.com
    entity: me_myself_and_i
    files_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\files
    force: null
    git_commit: null
    git_remote: origin
    git_remote_url: null
    git_root: null
    heartbeat_seconds: 30
    host: CorinaLaptop
    ignore_globs: []
    init_timeout: 90.0
    is_local: false
    job_name: null
    job_source: null
    label_disable: null
    launch: null
    launch_config_path: null
    log_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\logs
    log_internal: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\logs\debug-internal.log
    log_symlink_internal: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\debug-internal.log
    log_symlink_user: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\debug.log
    log_user: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\logs\debug.log
    login_timeout: null
    mode: online
    notebook_name: null
    problem: fatal
    program: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\main.py
    program_abspath: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\main.py
    program_relpath: main.py
    project: pytorch-sweeps-demo
    project_url: https://wandb.ai/me_myself_and_i/pytorch-sweeps-demo
    quiet: null
    reinit: null
    relogin: null
    resume: null
    resume_fname: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\wandb-resume.json
    resumed: false
    root_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5
    run_group: null
    run_id: bnwqk1v1
    run_job_type: null
    run_mode: run
    run_name: flowing-sweep-6
    run_notes: null
    run_tags: null
    run_url: https://wandb.ai/me_myself_and_i/pytorch-sweeps-demo/runs/bnwqk1v1
    sagemaker_disable: null
    save_code: null
    settings_system: C:\Users\dimit\.config\wandb\settings
    settings_workspace: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\settings
    show_colors: null
    show_emoji: null
    show_errors: true
    show_info: true
    show_warnings: true
    silent: false
    start_method: null
    strict: null
    summary_errors: null
    summary_timeout: 60
    summary_warnings: 5
    sweep_id: boz8zbft
    sweep_param_path: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\sweep-boz8zbft\config-bnwqk1v1.yaml
    sweep_url: https://wandb.ai/me_myself_and_i/pytorch-sweeps-demo/sweeps/boz8zbft
    symlink: false
    sync_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1
    sync_file: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\run-bnwqk1v1.wandb
    sync_symlink_latest: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\latest-run
    system_sample: 15
    system_sample_seconds: 2
    table_raise_on_max_row_limit_exceeded: false
    timespec: '20231106_171745'
    tmp_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\run-20231106_171745-bnwqk1v1\tmp
    username: dimit
    wandb_dir: D:\Facultate\Retele_Neuronale_Avansate\Mediu_de_Lucru\Assignment5\wandb\
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699283943.089187
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.4
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
